Update devops_Scan.yml

diff --git a/.github/workflows/devops_Scan.yml b/.github/workflows/devops_Scan.yml
--- a/.github/workflows/devops_Scan.yml
+++ b/.github/workflows/devops_Scan.yml
@@ -2,10 +2,10 @@ on:
   push:
     branches:
       - "**"
-
+ 
 jobs:
   quality-gate-code-check:
-    runs-on: ubuntu
+    runs-on: ubuntu-latest
     outputs:
       scanner-report-path: ${{ steps.upload-report.outputs.artifact-path }}
       block-pr: ${{ steps.block-check.outputs.block-status }}
@@ -88,7 +88,7 @@ jobs:
           fi
           for file in $files; do
             echo "Running SFDX Scanner on file: $file"
-            sf scanner:run --target "$file" --format "csv" --outfile "scanner-report.csv" || { echo "Scanner run failed for $file, continuing with other files."; }
+            sf scanner:run --target "$file" --format "csv" --outfile "scanner-report.csv" --ruleset "force-app/main/default/Custom_apex_ruleset.xml" || { echo "Scanner run failed for $file, continuing with other files."; }
           done
  
       - name: Block PR merge if severity violations are found
@@ -113,13 +113,13 @@ jobs:
       - name: Upload Scanner Report
         id: upload-report
         if: always()
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@v3
         with:
           name: SFDX_Code_Scan_Report
           path: scanner-report.csv
  
   quality-gate-critical-permissions-check:
-     runs-on: ubuntu
+    runs-on: ubuntu-latest
     needs: quality-gate-code-check
     if: ${{ needs.quality-gate-code-check.outputs.block-pr == 'false' }}
     steps:
@@ -127,7 +127,7 @@ jobs:
         uses: actions/checkout@v3
  
       - name: Download Scanner Report
-        uses: actions/download-artifact@v4
+        uses: actions/download-artifact@v3
         with:
           name: SFDX_Code_Scan_Report
  
