Update devops_pull_scan.yml

diff --git a/.github/workflows/devops_pull_scan.yml b/.github/workflows/devops_pull_scan.yml
--- a/.github/workflows/devops_pull_scan.yml
+++ b/.github/workflows/devops_pull_scan.yml
@@ -18,6 +18,16 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: 20.x
+
+      - name: Check and Install npm
+        run: |
+          if ! command -v npm &> /dev/null; then
+            echo "npm not found. Installing npm..."
+            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
+            sudo apt-get install -y nodejs
+          else
+            echo "npm is already installed. Version: $(npm --version)"
+          fi
  
       - name: Install Salesforce CLI
         run: npm install @salesforce/cli --global
@@ -151,9 +161,10 @@ jobs:
           done
           if [ ${#BLOCKED_FILES[@]} -gt 0 ]; then
             echo "Critical permissions found in the following files:"
-            for FILE in "${BLOCKED_FILES[@]}"; do
-              echo "$FILE"
+            for PERMISSION_INFO in "${CRITICAL_FOUND[@]}"; do
+              echo "$PERMISSION_INFO"
             done
+            echo "Blocking job due to critical permissions being assigned."
             exit 1
           else
             echo "No critical permissions assigned to non-System Administrator profiles or permission sets."
