Integrated Salesforce

diff --git a/.github/workflows/devops_Scan.yml b/.github/workflows/devops_Scan.yml
--- a/.github/workflows/devops_Scan.yml
+++ b/.github/workflows/devops_Scan.yml
@@ -91,25 +91,26 @@ jobs:
       - name: Upload Scanner Report to Salesforce
         if: success()
         run: |
-          if [ -s scanner-report.csv ]; then
-            response=$(curl -X POST "https://sprintparkllc4-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/ContentVersion" \
-              -H "Authorization: Bearer $SF_ACCESS_TOKEN" \
-              -H "Content-Type: multipart/form-data" \
-              -F "Title=${{ env.FILE_TITLE }}" \
-              -F "PathOnClient=scanner-report.csv" \
-              -F "VersionData=@scanner-report.csv")
-            echo "Upload Response: $response"
-
-            contentVersionId=$(echo $response | jq -r '.id // empty')
-            if [ -z "$contentVersionId" ]; then
-              echo "Error: Failed to upload file."
+            if [ -s scanner-report.csv ]; then
+              response=$(curl -X POST "https://sprintparkllc4-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/ContentVersion" \
+                -H "Authorization: Bearer $SF_ACCESS_TOKEN" \
+                -H "Content-Type: multipart/form-data" \
+                -F "entity_content={\"Title\": \"${{ env.FILE_TITLE }}\", \"PathOnClient\": \"scanner-report.csv\"};type=application/json" \
+                -F "VersionData=@scanner-report.csv;type=text/csv")
+                
+              echo "Upload Response: $response"
+        
+              contentVersionId=$(echo "$response" | jq -r '.id // empty')
+              if [ -z "$contentVersionId" ]; then
+                echo "Error: Failed to upload file."
+                exit 1
+              fi
+              echo "ContentVersionId: $contentVersionId" >> $GITHUB_ENV
+            else
+              echo "No scanner report generated, skipping upload."
               exit 1
             fi
-            echo "ContentVersionId: $contentVersionId" >> $GITHUB_ENV
-          else
-            echo "No scanner report generated, skipping upload."
-            exit 1
-          fi
+        
 
       - name: Upload Scanner Report as Artifact
         id: upload-report
