Version

diff --git a/.github/workflows/devops_Scan.yml b/.github/workflows/devops_Scan.yml
--- a/.github/workflows/devops_Scan.yml
+++ b/.github/workflows/devops_Scan.yml
@@ -46,17 +46,14 @@ jobs:
         with:
           node-version: 20.x
 
-      - name: Install Salesforce CLI
-        run: npm install @salesforce/cli --global
+      - name: Install Salesforce CLI v5 (Code Analyzer bundled)
+        run: npm install @salesforce/cli@latest --global
 
-      - name: Install Scanner Plugin
-        run: sf plugins install @salesforce/sfdx-scanner
+      # - name: Install Scanner Plugin
+      #   run: sf plugins install @salesforce/sfdx-scanner
 
       - name: Verify Salesforce CLI Installation
         run: sf --version
-
-      - name: Install Salesforce Code Analyzer v5
-        run: sf plugins install @salesforce/code-analyzer@latest
 
 
       - name: Get Commit Author
@@ -344,10 +341,11 @@ jobs:
 
             # Determine if it's Apex and needs ruleset config
             if [[ "$SCAN_PATH" == *.cls ]]; then
-              sf codeanalyzer run --target "$SCAN_PATH" --engine pmd --format "csv" --outfile "scanner-report-partial.csv" --pmdconfig "force-app/main/default/Custom_apex_ruleset.xml" || echo "⚠️ Scanner failed for $SCAN_PATH"
+              sf codeanalyzer run --target "$SCAN_PATH" --engine pmd --format csv --outfile scanner-report-partial.csv --pmdconfig force-app/main/default/Custom_apex_ruleset.xml || echo "⚠️ Scanner failed for $SCAN_PATH"
             else
-              sf codeanalyzer run --target "$SCAN_PATH" --engine eslint --format "csv" --outfile "scanner-report-partial.csv" || echo "⚠️ Scanner failed for $SCAN_PATH"
+              sf codeanalyzer run --target "$SCAN_PATH" --engine eslint --format csv --outfile scanner-report-partial.csv || echo "⚠️ Scanner failed for $SCAN_PATH"
             fi
+
 
 
             if [ -f "scanner-report-partial.csv" ] && [ -s "scanner-report-partial.csv" ]; then
