Update devops_Scan.yml

diff --git a/.github/workflows/devops_Scan.yml b/.github/workflows/devops_Scan.yml
--- a/.github/workflows/devops_Scan.yml
+++ b/.github/workflows/devops_Scan.yml
@@ -88,7 +88,7 @@ jobs:
           fi
           for file in $files; do
             echo "Running SFDX Scanner on file: $file"
-            sf scanner:run --target "$file" --format "csv" --outfile "scanner-report.csv" --ruleset "force-app/main/default/Custom_apex_ruleset.xml" || { echo "Scanner run failed for $file, continuing with other files."; }
+            sf scanner:run --target "$file" --format "csv" --outfile "scanner-report.csv" || { echo "Scanner run failed for $file, continuing with other files."; }
           done
  
       - name: Block PR merge if severity violations are found
@@ -113,21 +113,21 @@ jobs:
       - name: Upload Scanner Report
         id: upload-report
         if: always()
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: SFDX_Code_Scan_Report
           path: scanner-report.csv
  
   quality-gate-critical-permissions-check:
     runs-on: ubuntu-latest
-    needs: quality-gate-code-check
-    if: ${{ needs.quality-gate-code-check.outputs.block-pr == 'false' }}
+    # needs: quality-gate-code-check
+    # if: ${{ needs.quality-gate-code-check.outputs.block-pr == 'false' }}
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
  
       - name: Download Scanner Report
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4
         with:
           name: SFDX_Code_Scan_Report
  
