Delta Report

diff --git a/.github/workflows/devops_Scan.yml b/.github/workflows/devops_Scan.yml
--- a/.github/workflows/devops_Scan.yml
+++ b/.github/workflows/devops_Scan.yml
@@ -182,24 +182,24 @@ jobs:
           name: SFDX_Code_Scan_Report
           path: scanner-report.csv
 
-      - name: Block PR merge if severity 3 violations are found
+      # ✅ MOVE BLOCKING COMMIT STEP TO THE LAST STEP
+      - name: Block PR merge if severity violations are found
         id: block-check
         run: |
-            if [ -f scanner-report.csv ]; then
-              severity_fail_count=$(awk -F',' '{if ($2 == "3") count++} END {print count}' scanner-report.csv)
-              echo "Severity 3 Issues Count: $severity_fail_count"
-        
-              if [ "$severity_fail_count" -gt 0 ]; then
-                echo "Blocking commit due to severity 3 vulnerabilities found."
-                exit 1
-              else
-                echo "No severity 3 vulnerabilities found. Proceeding."
-              fi
+          if [ -f scanner-report.csv ]; then
+            severity_fail_count=$(awk -F',' '{gsub(/^ *| *$/, "", $2); if($2 == "\"3\"") count++} END {print count}' scanner-report.csv)
+            echo "Severity 3 issues count: $severity_fail_count"
+            
+            if [ "$severity_fail_count" -gt 0 ]; then
+              echo "Blocking commit due to severity 3 vulnerabilities found."
+              exit 1  # ✅ Now workflow fails only at the last step
             else
-              echo "No scanner report found."
-              exit 0
+              echo "No severity 3 vulnerabilities found. Proceeding with Approval."
             fi
-        
+          else
+            echo "No scanner report found."
+            exit 1
+          fi
 
 
   quality-gate-critical-permissions-check:
