Version Update

diff --git a/.github/workflows/devops_Scan.yml b/.github/workflows/devops_Scan.yml
--- a/.github/workflows/devops_Scan.yml
+++ b/.github/workflows/devops_Scan.yml
@@ -49,8 +49,17 @@ jobs:
       - name: Install Salesforce CLI
         run: npm install @salesforce/cli --global
 
-      - name: Install Scanner Plugin
-        run: sf plugins install @salesforce/sfdx-scanner
+      # - name: Install Scanner Plugin
+      #   run: sf plugins install @salesforce/sfdx-scanner
+
+      - name: Install Code Analyzer (v5)
+        run: sf plugins install @salesforce/code-analyzer
+
+      - name: Add PMD Custom Ruleset (Optional)
+        run: |
+          sf codeanalyzer rule:add --engine pmd --path force-app/main/default/Custom_apex_ruleset.xml || echo "Custom rules already added or not needed."
+
+
 
       - name: Verify Salesforce CLI Installation
         run: sf --version
@@ -340,9 +349,13 @@ jobs:
 
             # Determine if it's Apex and needs ruleset config
             if [[ "$SCAN_PATH" == *.cls ]]; then
-              sf scanner:run --target "$SCAN_PATH" --format "csv" --outfile "scanner-report-partial.csv" --pmdconfig "force-app/main/default/Custom_apex_ruleset.xml" || echo "⚠️ Scanner failed for $SCAN_PATH"
+              # sf scanner:run --target "$SCAN_PATH" --format "csv" --outfile "scanner-report-partial.csv" --pmdconfig "force-app/main/default/Custom_apex_ruleset.xml" || echo "⚠️ Scanner failed for $SCAN_PATH"
+              sf codeanalyzer run --target "$SCAN_PATH" --engine "pmd-custom,retire-js" --format "csv" --outfile "scanner-report-partial.csv" --pmdconfig "force-app/main/default/Custom_apex_ruleset.xml"
+
             else
-              sf scanner:run --target "$SCAN_PATH" --format "csv" --outfile "scanner-report-partial.csv" || echo "⚠️ Scanner failed for $SCAN_PATH"
+              # sf scanner:run --target "$SCAN_PATH" --format "csv" --outfile "scanner-report-partial.csv" || echo "⚠️ Scanner failed for $SCAN_PATH"
+              sf codeanalyzer run --target "$SCAN_PATH" --engine "retire-js" --format "csv" --outfile "scanner-report-partial.csv"
+
             fi
 
             if [ -f "scanner-report-partial.csv" ] && [ -s "scanner-report-partial.csv" ]; then
