Changed Demo.cls

diff --git a/.github/workflows/devops_Scan.yml b/.github/workflows/devops_Scan.yml
--- a/.github/workflows/devops_Scan.yml
+++ b/.github/workflows/devops_Scan.yml
@@ -88,8 +88,7 @@ jobs:
           fi
           for file in $files; do
             echo "Running SFDX Scanner on file: $file"
-            #sf scanner:run --target "$file" --format "csv" --outfile "scanner-report.csv" --ruleset "/force-app/main/default/Custom_apex_ruleset.xml" || { echo "Scanner run failed for $file, continuing with other files."; }
-            sf scanner:run --format "csv" --target ./force-app/main/default/classes/Demo.cls --pmdconfig ./force-app/main/default/Custom_apex_ruleset.xml > ./force-app/main/default/scanner-report.csv || { echo "Scanner run failed for $file, continuing with other files."; }
+            sf scanner:run --target "$file" --format "csv" --outfile "scanner-report.csv" --ruleset "/force-app/main/default/Custom_apex_ruleset.xml" || { echo "Scanner run failed for $file, continuing with other files."; }
           done
  
       - name: Block PR merge if severity violations are found
@@ -121,8 +120,8 @@ jobs:
  
   quality-gate-critical-permissions-check:
     runs-on: ubuntu-latest
-    # needs: quality-gate-code-check
-    # if: ${{ needs.quality-gate-code-check.outputs.block-pr == 'false' }}
+    needs: quality-gate-code-check
+    if: ${{ needs.quality-gate-code-check.outputs.block-pr == 'false' }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
